name: art
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.8  # Change to match your GPU driver, or remove for CPU
  - pip:
      - transformers
      - datasets
      - peft
      - bitsandbytes
      - accelerate
      - wandb
      - vllm
